services:
  contact:
    image: crdt-app
    container_name: contact
    command: ["java", "-jar", "app.jar", "HyParView.contact=none", "babel.interface=eth0", "-conf", "contact.conf"]
    networks:
      - cluster
    volumes:
      - ./logs/contact:/app/logs
    # mem_limit: 512m
    # cpus: 0.25

  node:
    image: crdt-app
    depends_on:
      - contact
    command: ["sh", "-c", "sleep 2 && java -jar app.jar HyParView.contact=contact:5555 babel.interface=eth0"]
    networks:
      - cluster
    volumes:
      - ./logs:/app/logs
    # mem_limit: 512m
    # cpus: 0.25

networks:
  cluster:
    driver: bridge